# Generated by Django 5.0.1 on 2024-02-11 08:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0003_carts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Oders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField(auto_now_add=True)),
                ('address', models.TextField(max_length=255)),
                ('status', models.CharField(choices=[('order-placed', 'order-placed'), ('cancelled', 'canecelled'), ('dispatched', 'dispatched'), ('deliverd', 'deliverd')], default='order-placed', max_length=300)),
                ('carts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecom.carts')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
