# Generated by Django 5.0.1 on 2024-02-13 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0004_oders'),
    ]

    operations = [
        migrations.AddField(
            model_name='oders',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
